/*
 * Copyright 2026 Morphe.
 * https://github.com/MorpheApp/morphe-manager
 *
 * Original hard forked code:
 * https://github.com/Jman-Github/Universal-ReVanced-Manager/blob/597b3173a004f5a9aae54326046dd7fd4c5b7777/app/src/main/java/app/revanced/manager/ui/theme/Color.kt
 *
 * See the included NOTICE file for GPLv3 Section 7 terms that apply to Morphe contributions.
 */

package app.morphe.manager.ui.theme

import androidx.compose.ui.graphics.Color

/** Morphe's brand blue, where its gradient starts. */
val MorpheBrandBlue = Color(0xFF1E5AA8)

/** Morphe's brand teal, where its gradient ends. */
val MorpheBrandTeal = Color(0xFF00AFAE)

val theme_light_primary = Color(0xFF005FAC)
val theme_light_onPrimary = Color(0xFFFFFFFF)
val theme_light_primaryContainer = Color(0xFFD4E3FF)
val theme_light_onPrimaryContainer = Color(0xFF001C39)
val theme_light_secondary = Color(0xFF545F71)
val theme_light_onSecondary = Color(0xFFFFFFFF)
val theme_light_secondaryContainer = Color(0xFFD8E3F8)
val theme_light_onSecondaryContainer = Color(0xFF111C2B)
val theme_light_tertiary = Color(0xFF6D5677)
val theme_light_onTertiary = Color(0xFFFFFFFF)
val theme_light_tertiaryContainer = Color(0xFFF6D9FF)
val theme_light_onTertiaryContainer = Color(0xFF271430)
val theme_light_error = Color(0xFFBA1A1A)
val theme_light_errorContainer = Color(0xFFFFDAD6)
val theme_light_onError = Color(0xFFFFFFFF)
val theme_light_onErrorContainer = Color(0xFF410002)
val theme_light_warning = Color(0xFF7C5800)
val theme_light_warningContainer = Color(0xFFFFDEA8)
val theme_light_onWarningContainer = Color(0xFF271900)
val theme_light_success = Color(0xFF286C2A)
val theme_light_successContainer = Color(0xFFABF5A3)
val theme_light_onSuccessContainer = Color(0xFF002204)
val theme_light_background = Color(0xFFFDFCFF)
val theme_light_onBackground = Color(0xFF1A1C1E)
val theme_light_surface = Color(0xFFFDFCFF)
val theme_light_onSurface = Color(0xFF1A1C1E)
val theme_light_surfaceVariant = Color(0xFFDFE2EB)
val theme_light_onSurfaceVariant = Color(0xFF43474E)
val theme_light_outline = Color(0xFF73777F)
val theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val theme_light_inverseSurface = Color(0xFF2F3033)
val theme_light_inversePrimary = Color(0xFFA4C9FF)
//val theme_light_shadow = Color(0xFF000000)
val theme_light_surfaceTint = Color(0xFF005FAC)
val theme_light_outlineVariant = Color(0xFFC3C6CF)
val theme_light_scrim = Color(0xFF000000)

val theme_dark_primary = Color(0xFFA4C9FF)
val theme_dark_onPrimary = Color(0xFF00315D)
val theme_dark_primaryContainer = Color(0xFF004884)
val theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
val theme_dark_secondary = Color(0xFFBCC7DB)
val theme_dark_onSecondary = Color(0xFF263141)
val theme_dark_secondaryContainer = Color(0xFF3D4758)
val theme_dark_onSecondaryContainer = Color(0xFFD8E3F8)
val theme_dark_tertiary = Color(0xFFD9BDE3)
val theme_dark_onTertiary = Color(0xFF3D2946)
val theme_dark_tertiaryContainer = Color(0xFF543F5E)
val theme_dark_onTertiaryContainer = Color(0xFFF6D9FF)
val theme_dark_error = Color(0xFFFFB4AB)
val theme_dark_errorContainer = Color(0xFF93000A)
val theme_dark_onError = Color(0xFF690005)
val theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val theme_dark_warning = Color(0xFFF5BD48)
val theme_dark_warningContainer = Color(0xFF5F4100)
val theme_dark_onWarningContainer = Color(0xFFFFDEA8)
val theme_dark_success = Color(0xFF90D889)
val theme_dark_successContainer = Color(0xFF0D5316)
val theme_dark_onSuccessContainer = Color(0xFFABF5A3)
val theme_dark_background = Color(0xFF1A1C1E)
val theme_dark_onBackground = Color(0xFFE3E2E6)
val theme_dark_surface = Color(0xFF1A1C1E)
val theme_dark_onSurface = Color(0xFFE3E2E6)
val theme_dark_surfaceVariant = Color(0xFF43474E)
val theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
val theme_dark_outline = Color(0xFF8D9199)
val theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val theme_dark_inverseSurface = Color(0xFFE3E2E6)
val theme_dark_inversePrimary = Color(0xFF005FAC)
//val theme_dark_shadow = Color(0xFF000000)
val theme_dark_surfaceTint = Color(0xFFA4C9FF)
val theme_dark_outlineVariant = Color(0xFF43474E)
val theme_dark_scrim = Color(0xFF000000)

val monochrome_light_primary = Color(0xFF565E68)
val monochrome_light_onPrimary = Color(0xFFFFFFFF)
val monochrome_light_primaryContainer = Color(0xFFDDE3EA)
val monochrome_light_onPrimaryContainer = Color(0xFF141B22)
val monochrome_light_secondary = Color(0xFF5B6170)
val monochrome_light_onSecondary = Color(0xFFFFFFFF)
val monochrome_light_secondaryContainer = Color(0xFFE0E4EA)
val monochrome_light_onSecondaryContainer = Color(0xFF181D28)
val monochrome_light_tertiary = Color(0xFF60616A)
val monochrome_light_onTertiary = Color(0xFFFFFFFF)
val monochrome_light_tertiaryContainer = Color(0xFFE4E5EC)
val monochrome_light_onTertiaryContainer = Color(0xFF1B1D24)
val monochrome_light_background = Color(0xFFF7F8FC)
val monochrome_light_onBackground = Color(0xFF191B20)
val monochrome_light_surface = Color(0xFFFFFFFF)
val monochrome_light_onSurface = Color(0xFF191B20)
val monochrome_light_surfaceVariant = Color(0xFFE7EAF1)
val monochrome_light_onSurfaceVariant = Color(0xFF444852)
val monochrome_light_outline = Color(0xFF747984)
val monochrome_light_outlineVariant = Color(0xFFC5C9D2)
val monochrome_light_inverseOnSurface = Color(0xFFF1F2F7)
val monochrome_light_inverseSurface = Color(0xFF2E3035)
val monochrome_light_inversePrimary = Color(0xFFC8CED8)
val monochrome_light_surfaceTint = Color(0xFF565E68)
val monochrome_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val monochrome_light_surfaceContainerLow = Color(0xFFF2F4F9)
val monochrome_light_surfaceContainer = Color(0xFFEEF1F7)
val monochrome_light_surfaceContainerHigh = Color(0xFFE9ECF3)
val monochrome_light_surfaceContainerHighest = Color(0xFFE3E6EE)
val monochrome_light_surfaceBright = Color(0xFFFFFFFF)
val monochrome_light_surfaceDim = Color(0xFFD9DDE5)

val monochrome_dark_primary = Color(0xFFC8CED8)
val monochrome_dark_onPrimary = Color(0xFF29313A)
val monochrome_dark_primaryContainer = Color(0xFF3E4650)
val monochrome_dark_onPrimaryContainer = Color(0xFFE3E8EF)
val monochrome_dark_secondary = Color(0xFFC4C9D8)
val monochrome_dark_onSecondary = Color(0xFF2D323D)
val monochrome_dark_secondaryContainer = Color(0xFF434956)
val monochrome_dark_onSecondaryContainer = Color(0xFFE0E5F2)
val monochrome_dark_tertiary = Color(0xFFC8CBD3)
val monochrome_dark_onTertiary = Color(0xFF2F3138)
val monochrome_dark_tertiaryContainer = Color(0xFF464852)
val monochrome_dark_onTertiaryContainer = Color(0xFFE5E7EF)
val monochrome_dark_background = Color(0xFF0B0C10)
val monochrome_dark_onBackground = Color(0xFFE4E6EC)
val monochrome_dark_surface = Color(0xFF131418)
val monochrome_dark_onSurface = Color(0xFFE4E6EC)
val monochrome_dark_surfaceVariant = Color(0xFF444852)
val monochrome_dark_onSurfaceVariant = Color(0xFFC5C9D2)
val monochrome_dark_outline = Color(0xFF8E929C)
val monochrome_dark_outlineVariant = Color(0xFF444852)
val monochrome_dark_inverseOnSurface = Color(0xFF191B20)
val monochrome_dark_inverseSurface = Color(0xFFE4E6EC)
val monochrome_dark_inversePrimary = Color(0xFF565E68)
val monochrome_dark_surfaceTint = Color(0xFFC8CED8)
val monochrome_dark_surfaceContainerLowest = Color(0xFF06070A)
val monochrome_dark_surfaceContainerLow = Color(0xFF111216)
val monochrome_dark_surfaceContainer = Color(0xFF17191E)
val monochrome_dark_surfaceContainerHigh = Color(0xFF202228)
val monochrome_dark_surfaceContainerHighest = Color(0xFF2B2E35)
val monochrome_dark_surfaceBright = Color(0xFF383B43)
val monochrome_dark_surfaceDim = Color(0xFF0B0C10)
